travis:
  secure:
    BINSTAR_TOKEN: s9NKOtF4S/5Z5NDPIbnUUotuVABWY6YJaCAgvOrCGVQXDuZSMFtzioPL75tCkgwzfVeksEcNJZbUVAPdAGg7CG3JtVMskghSjwyH5aby1vF5TxExqz2mnVFSal59SUOP6MbYKz087v/eWOCIn7j0Y468Wyf4TKJrdjS82IicXM/630VX3vlO5kG/c8DNIA0/gWxVNWUSCeyE1tZdmtJxXrlO5dn5/oW5ctpTG0E1DVC/AI0nAaOl8ENARSDqBlVYcAIY9TF9S5OowMSt3ntS2rHe/XP4DpLlQk/vT1w9oEL94rzEo+id90X0RBdxo1a+ZCO4yNSyP0bYcaZZm6OhRUAhcZFyUrqWeY81bPHxNoNQr1laLfX8gwoHG6j5dspu06JcEFNPBs4f8bovNU7QorKtnyqWSD/sefc++7jAwl4tj309sDDcVRsYH8jlWx81h46JJ89NEsSRQQjuWTA/CjBTzUDyHoLq4DZ7JWEU8p7RcqSn4NHEReJQLn0Q43cTutFlmPDcw+m5wRx1tfKFLORwE2maK2ZNSK3+7+DcxqxRGZdquUhPZ/cmteb32QqIs+VbpgUpMdBtvFVyxUYHXnf+S7oeQcnitWaQbUBHRTsrdSTsWI5/t5nbnG2EBVwG/5im6otxovTBfvgU/9YfCMPg5AydlNXX2I0lKMoc9lQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
