travis:
  secure:
    BINSTAR_TOKEN: Q934S6hSLKDr1/TLMU7AzQ9uz+8uHOrLplsGbGGsDZ38RvYavcNL4MLwdKH32o9eY94c2wRyFFHpW1hLSN4n08U9DXO71NVj+0ZjZ/RoIP0MRb8JU1hCFqVw98nogt9wLhY1rTGfjKS52LIPm3qbn9YNpdOf4rvahNShDKYYmcptFj0Jh2JRH4NWy+IJEIn1jwR55CfHTdho0pT46lGdFuyuilrPF55KxHhE1/zvky59HpZfdg/G3zCYLwxI3WsSrGL83Ly6Ltiw/4HAJjryYWJNH9D4js2FDW+PIoDhMub9mJ0KSxl9+BziKgVB7c450ZrMjT/T7YDe5FUngkX1AGP2OWj8RRNa1nFPw14xYk/1T7qc8W1WyrJu4T7Xj716wYdWmccf6ep3X+XMSlH5lWxAFJBLFzD4WyESsc/BpGpKdG5WE57DL3IaT5IcTJoD99pr/72Vej3CPYV6odCOitryHCB+4qzrHtRHZYqqLgiVrxvQVbYBUSmehaAQRccCiBkXpdeSXCe23MDie16NPQHezmoOPRUos6NkLOp+yOKTRBNTmRqw8+u9IomjI1Y0RYU8JmA48+VDXigoHX5N6x3Sn55JUCXOPciTD7nb7qOTzpMsDLgl7byxq9D7j7twJhY6k4FfFceXjFklrMaNILawCuCgz6STjS2wMWio3XY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
